import { AnimeMedia } from "./types";

export interface ResolvedStreamingLink {
  id?: string;
  site: string;
  url: string;
  type: "STREAMING" | "AUTO_RESOLVED";
  isAutoResolved: boolean;
  qualityBadge?: string;
}

export interface ResolvedEpisode {
  episodeNumber: number;
  title: string;
  thumbnail: string | null;
  url: string;
  site: string;
  airDateStr: string | null;
  isAired: boolean;
  isAutoGenerated: boolean;
}

/**
 * Standard known streaming platform search query builders
 */
export function buildStreamingSearchUrl(site: string, title: string, episodeNumber?: number): string {
  const encTitle = encodeURIComponent(title.trim());
  const query = episodeNumber ? encodeURIComponent(`${title.trim()} episode ${episodeNumber}`) : encTitle;

  switch (site.toLowerCase()) {
    case "crunchyroll":
      return `https://www.crunchyroll.com/search?q=${query}`;
    case "netflix":
      return `https://www.netflix.com/search?q=${encTitle}`;
    case "amazon prime video":
    case "prime video":
      return `https://www.amazon.com/s?k=${encTitle}+anime&i=instant-video`;
    case "hulu":
      return `https://www.hulu.com/search?q=${encTitle}`;
    case "youtube":
      return `https://www.youtube.com/results?search_query=${encodeURIComponent(`${title.trim()} ${episodeNumber ? `episode ${episodeNumber}` : "full episode 1 official"}`)}`;
    case "bilibili tv":
    case "bilibili":
      return `https://www.bilibili.tv/en/search-result?q=${encTitle}`;
    case "hidive":
      return `https://www.hidive.com/search?q=${encTitle}`;
    case "disney plus":
    case "disney+":
      return `https://www.disneyplus.com/search?q=${encTitle}`;
    default:
      return `https://www.google.com/search?q=${encodeURIComponent(`${title} watch anime online officially`)}`;
  }
}

/**
 * Automatically discovers & populates streaming providers if missing or incomplete
 */
export function resolveStreamingProviders(anime: AnimeMedia): ResolvedStreamingLink[] {
  const title = anime.title.english || anime.title.romaji;
  const existingLinks: ResolvedStreamingLink[] = (anime.externalLinks || [])
    .filter(
      (l) =>
        l.type === "STREAMING" ||
        ["Crunchyroll", "Netflix", "Hulu", "Amazon Prime Video", "Disney Plus", "HIDIVE", "Bilibili TV", "YouTube"].includes(
          l.site
        )
    )
    .map((l) => ({
      id: String(l.id || l.site),
      site: l.site,
      url: l.url,
      type: "STREAMING" as const,
      isAutoResolved: false,
      qualityBadge: "Official Catalog",
    }));

  // Deduplicate existing links by site name
  const deduplicated: ResolvedStreamingLink[] = [];
  const seenSites = new Set<string>();

  for (const item of existingLinks) {
    const key = item.site.toLowerCase().trim();
    if (!seenSites.has(key)) {
      seenSites.add(key);
      deduplicated.push(item);
    }
  }

  // Mandatory primary platforms to check & auto-resolve if missing
  const corePlatforms = [
    { site: "Crunchyroll", label: "Crunchyroll", badge: "Simulcast Hub" },
    { site: "Netflix", label: "Netflix", badge: "Global Streaming" },
    { site: "YouTube", label: "YouTube", badge: "Free Simulcasts" },
    { site: "Amazon Prime Video", label: "Amazon Prime Video", badge: "Prime Video" },
    { site: "Bilibili TV", label: "Bilibili TV", badge: "Official HD" },
  ];

  // If the title has fewer than 3 providers, automatically discover direct search catalog links
  for (const plat of corePlatforms) {
    const key = plat.site.toLowerCase().trim();
    if (!seenSites.has(key)) {
      seenSites.add(key);
      deduplicated.push({
        id: `auto-${plat.site.toLowerCase().replace(/\s+/g, "-")}`,
        site: plat.site,
        url: buildStreamingSearchUrl(plat.site, title),
        type: "AUTO_RESOLVED",
        isAutoResolved: true,
        qualityBadge: "Auto-Discovered",
      });
    }
  }

  return deduplicated;
}

/**
 * Format a timestamp into an English date string
 */
function formatTimestampToDate(timestampSec: number): string {
  try {
    const date = new Date(timestampSec * 1000);
    return date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return "";
  }
}

/**
 * Automatically discovers & builds complete episode guide with direct streaming URLs
 */
export function resolveEpisodeGuide(anime: AnimeMedia): ResolvedEpisode[] {
  const title = anime.title.english || anime.title.romaji;
  const primaryCrunchyroll = anime.externalLinks?.find((l) => l.site.toLowerCase() === "crunchyroll");
  const primaryStreamingUrl = primaryCrunchyroll?.url || null;

  // Case 1: AniList already has rich streamingEpisodes indexed
  if (anime.streamingEpisodes && anime.streamingEpisodes.length > 0) {
    return anime.streamingEpisodes.map((ep, idx) => {
      // Parse episode number from title like "Episode 1 - The Beginning"
      const numMatch = ep.title.match(/episode\s*(\d+)/i) || ep.title.match(/^(\d+)/);
      const epNum = numMatch ? parseInt(numMatch[1], 10) : idx + 1;

      return {
        episodeNumber: epNum,
        title: ep.title,
        thumbnail: ep.thumbnail || anime.bannerImage || anime.coverImage.extraLarge || anime.coverImage.large,
        url: ep.url,
        site: ep.site || "Crunchyroll",
        airDateStr: null,
        isAired: true,
        isAutoGenerated: false,
      };
    });
  }

  // Case 2: No streamingEpisodes in AniList API -> Automatically synthesize full episode directory
  const nextAirEp = anime.nextAiringEpisode;
  const nextAirNum = nextAirEp ? nextAirEp.episode : null;
  const isFinished = anime.status === "FINISHED";

  // Determine total episode count
  let totalCount = anime.episodes || 0;
  if (!totalCount) {
    if (nextAirNum) {
      totalCount = Math.max(12, nextAirNum + 3);
    } else if (anime.format === "MOVIE") {
      totalCount = 1;
    } else {
      totalCount = 12; // Standard single-cour seasonal anime
    }
  }

  // Calculate start air timestamp
  let baseAirTimestamp: number | null = null;
  if (anime.startDate?.year && anime.startDate?.month) {
    baseAirTimestamp = Date.UTC(
      anime.startDate.year,
      anime.startDate.month - 1,
      anime.startDate.day || 1
    ) / 1000;
  } else if (nextAirEp) {
    // Infer start from next episode
    baseAirTimestamp = nextAirEp.airingAt - (nextAirEp.episode - 1) * 7 * 86400;
  }

  const nowSec = Math.floor(Date.now() / 1000);
  const episodes: ResolvedEpisode[] = [];

  for (let i = 1; i <= totalCount; i++) {
    // Air timestamp calculation (+7 days per episode)
    const epAirTimestamp = baseAirTimestamp ? baseAirTimestamp + (i - 1) * 7 * 86400 : null;
    const airDateStr = epAirTimestamp ? formatTimestampToDate(epAirTimestamp) : null;

    // Check if episode has aired
    let isAired = false;
    if (isFinished) {
      isAired = true;
    } else if (nextAirNum) {
      isAired = i < nextAirNum;
    } else if (epAirTimestamp) {
      isAired = epAirTimestamp <= nowSec;
    } else {
      isAired = i === 1; // At least premiere if releasing
    }

    // Direct streaming URL auto-resolution
    let watchUrl = "";
    let providerSite = "Crunchyroll";

    if (primaryStreamingUrl && primaryStreamingUrl.includes("crunchyroll.com/series/")) {
      // Direct Crunchyroll series catalog
      watchUrl = primaryStreamingUrl;
    } else {
      // Auto-generated episode deep-search URL on Crunchyroll
      watchUrl = buildStreamingSearchUrl("Crunchyroll", title, i);
    }

    // Generate smart episode title
    let epTitle = `Episode ${i}`;
    if (i === 1) {
      epTitle = `Episode 1 — Series Premiere`;
    } else if (i === totalCount && totalCount > 1) {
      epTitle = `Episode ${i} — Season Finale`;
    }

    // Select thumbnail
    const thumbnail =
      anime.bannerImage ||
      anime.coverImage.extraLarge ||
      anime.coverImage.large ||
      null;

    episodes.push({
      episodeNumber: i,
      title: epTitle,
      thumbnail,
      url: watchUrl,
      site: providerSite,
      airDateStr,
      isAired,
      isAutoGenerated: true,
    });
  }

  return episodes;
}
