"use client";

import { useState, useMemo } from "react";
import {
  Tv,
  ExternalLink,
  Play,
  ChevronDown,
  ChevronUp,
  Clock,
  Sparkles,
  CheckCircle2,
  Search,
  Filter,
} from "lucide-react";
import { AnimeMedia } from "@/lib/types";
import { resolveEpisodeGuide, ResolvedEpisode } from "@/lib/streamingResolver";

interface EpisodeGuideProps {
  anime: AnimeMedia;
}

export default function EpisodeGuide({ anime }: EpisodeGuideProps) {
  const [showAll, setShowAll] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [activeFilter, setActiveFilter] = useState<"all" | "aired" | "upcoming">("all");

  // Automatically discover & populate episode catalog with working streaming URLs
  const allEpisodes = useMemo(() => {
    return resolveEpisodeGuide(anime);
  }, [anime]);

  const airedCount = allEpisodes.filter((e) => e.isAired).length;
  const upcomingCount = allEpisodes.length - airedCount;
  const isAutoGenerated = allEpisodes.some((e) => e.isAutoGenerated);

  // Filter episodes based on category and search query
  const filteredEpisodes = useMemo(() => {
    return allEpisodes.filter((ep) => {
      // Category filter
      if (activeFilter === "aired" && !ep.isAired) return false;
      if (activeFilter === "upcoming" && ep.isAired) return false;

      // Text search filter
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase().trim();
        const matchesTitle = ep.title.toLowerCase().includes(q);
        const matchesNum = String(ep.episodeNumber) === q || `ep ${ep.episodeNumber}` === q;
        return matchesTitle || matchesNum;
      }
      return true;
    });
  }, [allEpisodes, activeFilter, searchQuery]);

  const displayedEpisodes = showAll || searchQuery.trim() || activeFilter !== "all"
    ? filteredEpisodes
    : filteredEpisodes.slice(0, 8);

  if (allEpisodes.length === 0) return null;

  return (
    <section className="flex flex-col gap-5 rounded-2xl bg-[#131622] border border-[#222736] p-5 sm:p-6 shadow-sm">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#202533] pb-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-blue-600/10 border border-blue-500/20 flex items-center justify-center text-blue-400 flex-shrink-0">
            <Tv className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <h3 className="text-base sm:text-lg font-bold text-white tracking-tight">
                Episode Guide & Direct Stream Launchers
              </h3>
              <span className="text-xs text-blue-400 font-semibold px-2 py-0.5 rounded-full bg-blue-500/10 border border-blue-500/20">
                {allEpisodes.length} Episodes
              </span>
              {isAutoGenerated && (
                <span className="text-[10px] font-bold text-emerald-400 bg-emerald-500/15 border border-emerald-500/30 px-2 py-0.5 rounded-full flex items-center gap-1">
                  <Sparkles className="w-3 h-3 text-emerald-400" />
                  Auto-Discovered Watch Links
                </span>
              )}
            </div>
            <p className="text-xs text-gray-400 mt-0.5">
              Instant 1080p simulcast watch links with air dates and broadcast progression.
            </p>
          </div>
        </div>

        {/* Search Input */}
        {allEpisodes.length > 4 && (
          <div className="relative w-full sm:w-56">
            <Search className="w-3.5 h-3.5 text-gray-500 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search episode or #..."
              className="w-full pl-8 pr-3 py-1.5 rounded-lg bg-[#181d2a] border border-[#252c3e] text-xs text-gray-200 placeholder-gray-500 focus:outline-none focus:border-blue-500 transition-colors"
            />
          </div>
        )}
      </div>

      {/* Filter Chips Bar */}
      <div className="flex items-center justify-between gap-3 flex-wrap text-xs">
        <div className="flex items-center gap-2">
          <button
            onClick={() => setActiveFilter("all")}
            className={`px-3 py-1 rounded-lg font-semibold transition-colors cursor-pointer ${
              activeFilter === "all"
                ? "bg-blue-600 text-white font-bold"
                : "bg-[#181d2a] text-gray-400 hover:text-white border border-[#252c3e]"
            }`}
          >
            All Episodes ({allEpisodes.length})
          </button>
          <button
            onClick={() => setActiveFilter("aired")}
            className={`px-3 py-1 rounded-lg font-semibold transition-colors cursor-pointer flex items-center gap-1.5 ${
              activeFilter === "aired"
                ? "bg-emerald-600 text-white font-bold"
                : "bg-[#181d2a] text-emerald-400 hover:text-white border border-[#252c3e]"
            }`}
          >
            <CheckCircle2 className="w-3 h-3" />
            <span>Available to Stream ({airedCount})</span>
          </button>
          {upcomingCount > 0 && (
            <button
              onClick={() => setActiveFilter("upcoming")}
              className={`px-3 py-1 rounded-lg font-semibold transition-colors cursor-pointer flex items-center gap-1.5 ${
                activeFilter === "upcoming"
                  ? "bg-amber-600 text-white font-bold"
                  : "bg-[#181d2a] text-amber-400 hover:text-white border border-[#252c3e]"
              }`}
            >
              <Clock className="w-3 h-3" />
              <span>Upcoming ({upcomingCount})</span>
            </button>
          )}
        </div>

        <span className="text-[11px] text-gray-500">
          Showing {displayedEpisodes.length} of {filteredEpisodes.length}
        </span>
      </div>

      {/* Episode Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3.5">
        {displayedEpisodes.map((ep) => (
          <a
            key={ep.episodeNumber}
            href={ep.url}
            target="_blank"
            rel="noopener noreferrer"
            className="group rounded-xl bg-[#181c28] border border-[#252b3d] hover:border-blue-500/50 hover:bg-[#1a2030] overflow-hidden flex flex-col justify-between transition-all shadow-sm"
          >
            {/* Thumbnail */}
            <div className="relative aspect-video w-full bg-[#10131a] overflow-hidden">
              {ep.thumbnail ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={ep.thumbnail}
                  alt={ep.title}
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                  loading="lazy"
                />
              ) : (
                <div className="w-full h-full flex items-center justify-center bg-[#151924] text-gray-500">
                  <Tv className="w-8 h-8 opacity-40" />
                </div>
              )}

              {/* Episode Number Badge */}
              <div className="absolute top-2 left-2 px-2 py-0.5 rounded-md bg-black/80 backdrop-blur-xs text-[10px] font-black text-white border border-white/10 shadow-sm">
                EP {ep.episodeNumber < 10 ? `0${ep.episodeNumber}` : ep.episodeNumber}
              </div>

              {/* Status Badge */}
              <div className="absolute top-2 right-2">
                {ep.isAired ? (
                  <span className="px-2 py-0.5 rounded-md bg-emerald-500/90 text-[10px] font-bold text-gray-950 shadow-sm">
                    Stream Ready
                  </span>
                ) : (
                  <span className="px-2 py-0.5 rounded-md bg-amber-500/90 text-[10px] font-bold text-gray-950 shadow-sm flex items-center gap-1">
                    <Clock className="w-2.5 h-2.5" />
                    <span>Upcoming</span>
                  </span>
                )}
              </div>

              {/* Play Hover Overlay */}
              <div className="absolute inset-0 bg-black/45 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                <div className="w-10 h-10 rounded-full bg-blue-600 text-white flex items-center justify-center shadow-lg group-hover:scale-110 transition-transform">
                  <Play className="w-4 h-4 fill-white translate-x-0.5" />
                </div>
              </div>

              {/* Platform tag */}
              <span className="absolute bottom-2 right-2 px-2 py-0.5 rounded bg-black/80 text-[10px] font-semibold text-gray-300 border border-white/10">
                {ep.site}
              </span>
            </div>

            {/* Episode Title & Metadata */}
            <div className="p-3 flex flex-col gap-2 flex-1 justify-between">
              <div>
                <h4 className="text-xs font-bold text-gray-100 group-hover:text-blue-400 line-clamp-2 transition-colors">
                  {ep.title}
                </h4>
                {ep.airDateStr && (
                  <span className="text-[10px] text-gray-400 block mt-0.5">
                    Air Date: {ep.airDateStr}
                  </span>
                )}
              </div>

              <div className="flex items-center justify-between pt-2 text-[11px] border-t border-[#202534] mt-1 text-blue-400 group-hover:text-blue-300">
                <span className="font-semibold flex items-center gap-1">
                  <span>Watch on {ep.site}</span>
                </span>
                <ExternalLink className="w-3.5 h-3.5" />
              </div>
            </div>
          </a>
        ))}
      </div>

      {/* Show All / Show Less Button */}
      {filteredEpisodes.length > 8 && !searchQuery.trim() && (
        <div className="flex justify-center pt-2">
          <button
            onClick={() => setShowAll(!showAll)}
            className="px-4 py-2 rounded-lg bg-[#181c28] hover:bg-[#202534] text-xs font-semibold text-gray-300 hover:text-white border border-[#252b3d] transition-colors flex items-center gap-1.5 cursor-pointer"
          >
            {showAll ? (
              <>
                <ChevronUp className="w-3.5 h-3.5" />
                <span>Show Fewer Episodes</span>
              </>
            ) : (
              <>
                <ChevronDown className="w-3.5 h-3.5" />
                <span>Show All {filteredEpisodes.length} Episodes</span>
              </>
            )}
          </button>
        </div>
      )}
    </section>
  );
}
